apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  labels:
    app.kubernetes.io/component: kibana
  name: kibana-configmap
data:
  XPACK_AUTH_BASIC: "true"
  XPACK_MONITORING: "true"
  NAME: "kibana-k8s"
  OLD_DATA_IGNORE: "true"
  kibana.yml: |-
    server.host: 0.0.0.0

    elasticsearch:
      hosts: ${ELASTICSEARCH_HOSTS}
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}

---