apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
  namespace: default
  labels:
    app.kubernetes.io/component: kibana
spec:
  ports:
    - name: kibana-port
      port: 5601
      nodePort: 32601
  type: NodePort
  selector:
    app.kubernetes.io/component: kibana
