apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: auth-svc
  name: auth-svc
spec:
  selector:
    matchLabels:
      io.kompose.service: auth-svc
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: auth-svc
    spec:
      hostname: auth-svc-svc   
      restartPolicy: Always
      containers:
        - name: auth-svc-svc
          image: garild/tsp:auth-svc
          ports:
            - containerPort: 5010
              name: "auth-svc-port"
          resources: {}
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5010
            - name: SERVICE_NAME
              value: auth-svc
            - name: ASPNETCORE_ENVIRONMENT 
              value: "Production"
            - name: FLUENTD_LOG_PATH
              value: "/var/apps-logging/"
            - name: SERVICE_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ELASTICSEARCH_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: auth-configmap
                  key: elasticsearch-host
            - name: FLUENTD_HOST
              valueFrom:
                configMapKeyRef:
                  name: auth-configmap
                  key: fluentd-host
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-user-password
                  key: password
          volumeMounts:
          - name: test-volume
            mountPath: /var/apps-logging
      volumes:
      - name: test-volume
        hostPath:
          # directory location on host
          path:  /var/apps-logging
          # this field is optional
          type: Directory
status: {}
