apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: auth-svc
  name: auth-svc
spec:
  replicas: 3
  strategy: {}
  selector:
    matchLabels:
      app: auth-svc
  template:
    metadata:
      labels:
        app: auth-svc
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: auth-configmap
              key: environment
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef:
              name: auth-configmap
              key: services-host
        - name: ELASTICSEARCH_HOSTS
          valueFrom:
            configMapKeyRef:
              name: auth-configmap
              key: elasticsearch-host
        - name: FLUENTD_HOST
          valueFrom:
            configMapKeyRef:
              name: auth-configmap
              key: fluentd-host
        - name: HEALTHCHECK_URL
          valueFrom:
            configMapKeyRef:
              name: auth-configmap
              key: healthcheck-host
        image: garild/tsp:auth-svc
        name: auth-svc
        ports:
        - containerPort: 5010
        resources: {}
      hostname: auth-svc
      restartPolicy: Always
status: {}
