apiVersion: v1
kind: Service
metadata:
  labels:
    service: auth-svc
  name: auth-svc
spec:
  ports:
  - name: "5010"
    port: 5010
    targetPort: 5010
  selector:
    service: auth-svc
status:
  loadBalancer: {}
