apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f apps-develope-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: kibana-svc
  name: kibana-svc
spec:
  ports:
  - name: "5601"
    port: 5601
    targetPort: 5601
  selector:
    io.kompose.service: kibana-svc
status:
  loadBalancer: {}
