apiVersion: v1
data:
  ES_HOST: elasticsearch-svc
  ES_PORT: "9200"
  ES_SCHEME: "http"
  UID: "0"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: fluentd-config-map
  name: fluentd-config-map
