apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: default
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluentd-svc:local
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            valueFrom:
              configMapKeyRef:
                key: ES_HOST
                name: fluentd-config-map
          - name:  FLUENT_ELASTICSEARCH_PORT
            valueFrom:
              configMapKeyRef:
                key: ES_PORT
                name: fluentd-config-map
          - name: FLUENT_ELASTICSEARCH_SCHEME
            valueFrom:
              configMapKeyRef:
                key: ES_SCHEME
                name: fluentd-config-map
          - name: FLUENT_UID
            valueFrom:
              configMapKeyRef:
                key: UID
                name: fluentd-config-map
          # X-Pack Authentication
          # =====================
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers