apiVersion: v1
kind: Service
metadata:
  labels:
    service: elasticsearch-svc
  name: elasticsearch-svc
spec:
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
  selector:
    service: elasticsearch-svc
status:
  loadBalancer: {}
